use minifb::Key;

const KEYBOARD_PATH_PREFIX: &str = "keyboard.";

pub(super) fn input_path_from_key(key: Key) -> String {
    format!("{KEYBOARD_PATH_PREFIX}{key:?}")
}

pub(super) fn key_from_input_path(path: &str) -> Option<Key> {
    let raw = path.strip_prefix(KEYBOARD_PATH_PREFIX)?;
    all_keys().iter().copied().find(|key| format!("{key:?}") == raw)
}

fn all_keys() -> &'static [Key] {
    const ALL_KEYS: &[Key] = &[
        Key::Key0,
        Key::Key1,
        Key::Key2,
        Key::Key3,
        Key::Key4,
        Key::Key5,
        Key::Key6,
        Key::Key7,
        Key::Key8,
        Key::Key9,
        Key::A,
        Key::B,
        Key::C,
        Key::D,
        Key::E,
        Key::F,
        Key::G,
        Key::H,
        Key::I,
        Key::J,
        Key::K,
        Key::L,
        Key::M,
        Key::N,
        Key::O,
        Key::P,
        Key::Q,
        Key::R,
        Key::S,
        Key::T,
        Key::U,
        Key::V,
        Key::W,
        Key::X,
        Key::Y,
        Key::Z,
        Key::F1,
        Key::F2,
        Key::F3,
        Key::F4,
        Key::F5,
        Key::F6,
        Key::F7,
        Key::F8,
        Key::F9,
        Key::F10,
        Key::F11,
        Key::F12,
        Key::F13,
        Key::F14,
        Key::F15,
        Key::Down,
        Key::Left,
        Key::Right,
        Key::Up,
        Key::Apostrophe,
        Key::Backquote,
        Key::Backslash,
        Key::Comma,
        Key::Equal,
        Key::LeftBracket,
        Key::Minus,
        Key::Period,
        Key::RightBracket,
        Key::Semicolon,
        Key::Slash,
        Key::Backspace,
        Key::Delete,
        Key::End,
        Key::Enter,
        Key::Escape,
        Key::Home,
        Key::Insert,
        Key::Menu,
        Key::PageDown,
        Key::PageUp,
        Key::Pause,
        Key::Space,
        Key::Tab,
        Key::NumLock,
        Key::CapsLock,
        Key::ScrollLock,
        Key::LeftShift,
        Key::RightShift,
        Key::LeftCtrl,
        Key::RightCtrl,
        Key::NumPad0,
        Key::NumPad1,
        Key::NumPad2,
        Key::NumPad3,
        Key::NumPad4,
        Key::NumPad5,
        Key::NumPad6,
        Key::NumPad7,
        Key::NumPad8,
        Key::NumPad9,
        Key::NumPadDot,
        Key::NumPadSlash,
        Key::NumPadAsterisk,
        Key::NumPadMinus,
        Key::NumPadPlus,
        Key::NumPadEnter,
        Key::LeftAlt,
        Key::RightAlt,
        Key::LeftSuper,
        Key::RightSuper,
        Key::Unknown,
    ];

    ALL_KEYS
}
